/****************************************************************************/
/*                                                                          */
/* PROGRAM NAME: WKFInfo                                                    */
/*                                                                          */
/* COPYRIGHT:                                                               */
/* ----------                                                               */
/* Copyright (C) International Business Machines Corp., 1991,1992,1993,1994 */
/*                                                                          */
/* DISCLAIMER OF WARRANTIES:                                                */
/* -------------------------                                                */
/* The following [enclosed] code is sample code created by IBM              */
/* Corporation.  This sample code is not part of any standard IBM product   */
/* and is provided to you solely for the purpose of assisting you in the    */
/* development of your applications.  The code is provided "AS IS",         */
/* without warranty of any kind.  IBM shall not be liable for any damages   */
/* arising out of your use of the sample code, even if they have been       */
/* advised of the possibility of such damages.                              */
/*                                                                          */
/* REVISION LEVEL: 2.1                                                      */
/* -------------------                                                      */
/*                                                                          */
/* This program illustrates using the project and actions profile APIs to   */
/* obtain information about a project and its actions.                      */
/*                                                                          */
/****************************************************************************/
                                                                              

/* Include WF integration headers */  
#define INCL_WKFPRJ                          
#define INCL_WKFPRF                          
#define INCL_WKFPAM                          

#define IDD_DLG                     100
#define IDD_MLE                     FID_CLIENT

#define IDM_DLG_ACTIONBAR           200
#define IDM_FILE                    201
#define IDM_FILE_OPEN               202
#define IDM_FILE_SAVE               203

#define MAX_LINE_LENGTH             1000

  
  
  



















                                                                                      

