/*+--------------------------------------------------------------------------+*/
/*|WF/2 Message spy sample                                                   |*/
/*|--------------------------------------------------------------------------|*/
/*|                                                                          |*/
/*| PROGRAM NAME: WFPEEK                                                     |*/
/*| -------------                                                            |*/
/*|                                                                          |*/
/*| COPYRIGHT:                                                               |*/
/*| ----------                                                               |*/
/*|  Copyright (C) International Business Machines Corp., 1991,1992,1993.    |*/
/*|                                                                          |*/
/*| DISCLAIMER OF WARRANTIES:                                                |*/
/*| -------------------------                                                |*/
/*| The following [enclosed] code is sample code created by IBM              |*/
/*| Corporation.  This sample code is not part of any standard IBM product   |*/
/*| and is provided to you solely for the purpose of assisting you in the    |*/
/*| development of your applications.  The code is provided "AS IS",         |*/
/*| without warranty of any kind.  IBM shall not be liable for any damages   |*/
/*| arising out of your use of the sample code, even if they have been       |*/
/*| advised of the possibility of such damages.                              |*/
/*|                                                                          |*/
/*| REVISION LEVEL: 2.1                                                      |*/
/*| -------------------                                                      |*/
/*|                                                                          |*/
/*|  This program illustrates registering a PM program with WF/2 and         |*/
/*|  receiving messages from WF/2.                                           |*/
/*|                                                                          |*/
/*+--------------------------------------------------------------------------+*/
#ifndef __WFPEEK_H__
   #define __WFPEEK_H__

   #define IDD_WFPEEK_MAIN    100
   #define IDC_WFPEEK_LISTBOX (FID_CLIENT)
   #define IDS_WFPEEK_TITLE   102

   #define WKF_TYPE_UNKNOWN   0x1000000
#endif
